### ISSUE TITLE
Test and improve the performance on large files

### ISSUE THREAD

**Issue by physikerwelt** [ContemporaryArtwork/M-to-m#5]
Benchmark the performance of your programs for large files (e.g. 2GB)
Can you do the replacement without reading the entire file into memory?

**Comment by ContemporaryArtwork** [comment]
Do you have any links as to where I could get a 2GB text file?

**Comment by ContemporaryArtwork** [comment]
@physikerwelt @HowardCohl 
I pushed a program that generates text files of arbitrary size.

**Comment by ContemporaryArtwork** [comment]
At the moment it only writes a stream of characters on one line.

**Comment by ContemporaryArtwork** [comment]
@physikerwelt @HowardCohl 
I have pushed a program that reads without taking the whole file into memory.
Also I have changed the text file creator so it adds in a newline every 90 characters

**Comment by HowardCohl** [comment]
Can you generate a program which generates a normally distributed random integer with an average b between integers a and c>b?  If you can write this function then it could be used to create a word of random length. According to Wolfram|Alpha the average length of a word in english is 5.1 characters. http://www.wolframalpha.com/input/?i=average+english+word+length

**Comment by ContemporaryArtwork** [comment]
@HowardCohl 
I don't know what normal distribution means; I'll work on adding the things that you specified

**Comment by HowardCohl** [comment]
@ContemporaryArtwork Don't worry about that just use a uniform distribution. A random integer between two integers, for instance, random integer between 1 and x.

**Comment by ContemporaryArtwork** [comment]
@HowardCohl 
I updated the program to do some of what you asked

**Comment by HowardCohl** [comment]
@ContemporaryArtwork 
Can you give a detailed list of what you have done?
Did you insert random (double) carriage returns to model paragraphs?
Did you insert random spaces to model words?
Do you have a maximum line length?
Did you insert random punctuation after words?

Can you email me a sample output text file?

BTW, I found this link: http://superuser.com/questions/692175/how-to-create-a-random-txthuman-readable-text-like-ascii-file-in-linux

**Comment by ContemporaryArtwork** [comment]
1) The program inserts single carriage returns but I will make them double.
2) Yes
3) It's 90 but the spaces and periods add a little bit, I will fix that
4)Only periods as of now but I can add more.
5) Sure
[test.txt](https://github.com/ContemporaryArtwork/M-to-m/files/47877/test.txt)

**Comment by HowardCohl** [comment]
You should capitalize the first letter of the first word of every sentence and also sometimes capitalize the first letter of random words.

I like it!  Can you tell me the parameters you used and where you got them from?
e.g., random length of word, etc. give me them all.

**Comment by HowardCohl** [comment]
@physikerwelt @ContemporaryArtwork 

Should this issue be closed?  What do you think Moritz?

**Comment by ContemporaryArtwork** [comment]
1) length of the word is by a random number out of 7 or a number of 5 + random between 1 and 3.
2) length of sentences is 6 + number between 1 and 5
3) chance of new paragraph is between 3 sentences and 3 + number out of 5 sentences

**Comment by HowardCohl** [comment]
@ContemporaryArtwork 

You never said how you got these parameters.

**Comment by ContemporaryArtwork** [comment]
@HowardCohl 
Oops:

"According to Wolfram|Alpha the average length of a word in english is 5.1 characters."
so I made the number of letters in a word around there (between 1 and 7 or 5+1-3)

"The average number of words in a sentence might be taken as http://www.onlinegrammar.com.au/how-many-words-are-too-many-in-a-sentence/
Maybe 9-14. Or maybe 11.5."
so I made the number of words in a sentence 6 + 1-5

"http://www.wolframalpha.com/input/?i=average+english+word+length You could also have a paragraph of average length 5 lines. No need to indent I suspect."
so I made the number of lines in a paragraph 3 + 1-5

**Comment by ContemporaryArtwork** [comment]
So should I run MConvertStream on a large (2GB) file now that I (sorta?) have mvn exec up and running?

**Comment by ContemporaryArtwork** [comment]
Also, should I make the FIleMakeLine program headless so it can be run via maven?

**Comment by physikerwelt** [comment]
Hi... a lot of issues here.
Maybe we can arrange a google hangout meeting tomorrow?
Am 02.12.2015 03:34 schrieb "ContemporaryArtwork" <notifications@github.com
>:
>
> Also, should I make the FIleMakeLine program headless so it can be run
via maven?

**Comment by ContemporaryArtwork** [comment]
Sounds good, but when should it happen? Because I have school from 8 AM to 3PM, so somewhere around 3(or 9 for you)?

**Comment by HowardCohl** [comment]
@ContemporaryArtwork 

Set a time when you are available.  Maybe 3.30 pm?  Can you be available then?

**Comment by ContemporaryArtwork** [comment]
yep

**Comment by HowardCohl** [comment]
@physikerwelt @ContemporaryArtwork 

BTW, I won't be able to attend today because of a family obligation.  Hope your meeting is productive though!

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
Should this issue be closed now, or is there something that I'm missing?

**Comment by physikerwelt** [comment]
The issue was
"Benchmark the performance of your programs for large files (e.g. 2GB)
Can you do the replacement without reading the entire file into memory?"
Where can I read the results of the evaulation.
A benchmark should be reproducible by other so one usually writes
"I tested the program 10 times on a machine with hardware X and operating system Y and software versions (Java, Maven, ...) with the input Z generated by A. The average run time was B the STD deviation was C ..."

**Comment by ContemporaryArtwork** [comment]
@physikerwelt 
ah right, forgot about that actual large file part

**Comment by ContemporaryArtwork** [comment]
I tested the program 5 times on a machine with an i7-3630QM 2.40 GHZ and Windows 10 and software versions (Java - 1.7.0.45, Maven 3.3.9) with the input (a 2 GB text file) generated by the FileMakeLine program. The average run time was  19.004 minutes and the standard deviation was 11.460.

**Comment by HowardCohl** [comment]
The standard deviation was 11.460 minutes?

**Comment by ContemporaryArtwork** [comment]
@HowardCohl 
The deviation between times was  huge for me. The times for the same file ranged from 11.12 minutes to 36 minutes. It might not sound right but the time of processing varied greatly.

**Comment by HowardCohl** [comment]
@physikerwelt 
Does this sound right to you? How can there be such huge deviations in execution time?

@ContemporaryArtwork 
Were all those runs with the same input or different inputs?

**Comment by physikerwelt** [comment]
Another question... why does it take soo long?

**Comment by HowardCohl** [comment]
Also, how did you verify that it did actually what you wanted it to do.

Can you look at the first 100 lines, 100 lines in the middle , and 100 lines at the end, for the input and the output and compare them?

**Comment by physikerwelt** [comment]
@HowardCohl can you run the program on your computer?
How long does it take for you.
Is the documentation good enought so that you know how to run the code without looking at other sources beside the git readme... I'm not sure.

**Comment by HowardCohl** [comment]
I did some basic searches on the internet and saw that for a java program you should change to the directory of the java program and enter ``javac file.java``

I cloned the task and changed to the following directory where I found some .java files in ``/home/hcohl/testt/M-to-m/src/main/java/com/contemporaryartwork/mtoM``

then I entered the following (my machine is called whipple):

```
whipple:mtoM: javac FileMakeLine.java 
whipple:mtoM: ls
./  ../  FileMakeLine.class  FileMakeLine.java	MConvertStream.java
whipple:mtoM: java FileMakeLine
Exception in thread "main" java.lang.NoClassDefFoundError: FileMakeLine (wrong name: com/contemporaryartwork/mtoM/FileMakeLine)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```
Did I do it right Jake? Something seems wrong.  Can you give me some instructions to run it from the command line?  What directory do I change to and what command do I execute. I am using Linux.

**Comment by ContemporaryArtwork** [comment]
Try doing:

java FileMakeLine.java

in the same directory, also I'm going to make the FileMakeLine program not use the joptionframe so it can be run straight from the command line. Obviously I haven't tested FileMakeLine from linux so I will do so now and see if I get the same error. You're in the right directory, and try doing the command I indicated.

**Comment by physikerwelt** [comment]
I would recommend to use mvn exec like it's done on https://github.com/TU-Berlin/mathosphere/tree/master/restd
People have to use mvn anyhow to install the program

**Comment by ContemporaryArtwork** [comment]
"mvn clean install -DskipTests"

what does this do?

**Comment by physikerwelt** [comment]
https://www.google.de/search?q=mvn+clean+install+-DskipTests"what+does+this+do%3F
